version: '3.7'

services:
  web:
    build:
      context: ./client
      dockerfile: ./Dockerfile.web
    image: "rs3exch-web"
    stdin_open: true
    ports:
      - "3000:3000"
    links:
      - "worker"
    networks: 
      - node-react-network
  worker:
    build:
      context: ./server
      dockerfile: ./Dockerfile.worker
    image: "rs3exch-worker"
    ports:
      - "5000:5000"
    networks: 
      - node-react-network
    depends_on: 
      - postgres

networks: 
  node-react-network:
    name: rs3exch-network
    driver: bridge