version: '3.7'

services:
  node-react-starter-app:
    image: astro24/rs3-exch:prod
    build: 
      context: .
      target: prod
    container_name: node-react-starter-app
    restart: always
    volumes: 
      - .:/app
    ports:
      - "5000:5000"
      - "3000:3000"
    networks: 
      - node-react-starter-network

networks: 
  node-react-starter-network:
    name: node-react-starter-network